// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: proto/getVideoService.proto

package getVideoListService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetVideoListClient is the client API for GetVideoList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetVideoListClient interface {
	GetPlaylistItems(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getVideoListClient struct {
	cc grpc.ClientConnInterface
}

func NewGetVideoListClient(cc grpc.ClientConnInterface) GetVideoListClient {
	return &getVideoListClient{cc}
}

func (c *getVideoListClient) GetPlaylistItems(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/getVideoList/GetPlaylistItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetVideoListServer is the server API for GetVideoList service.
// All implementations must embed UnimplementedGetVideoListServer
// for forward compatibility
type GetVideoListServer interface {
	GetPlaylistItems(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGetVideoListServer()
}

// UnimplementedGetVideoListServer must be embedded to have forward compatible implementations.
type UnimplementedGetVideoListServer struct {
}

func (UnimplementedGetVideoListServer) GetPlaylistItems(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaylistItems not implemented")
}
func (UnimplementedGetVideoListServer) mustEmbedUnimplementedGetVideoListServer() {}

// UnsafeGetVideoListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetVideoListServer will
// result in compilation errors.
type UnsafeGetVideoListServer interface {
	mustEmbedUnimplementedGetVideoListServer()
}

func RegisterGetVideoListServer(s grpc.ServiceRegistrar, srv GetVideoListServer) {
	s.RegisterService(&GetVideoList_ServiceDesc, srv)
}

func _GetVideoList_GetPlaylistItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetVideoListServer).GetPlaylistItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getVideoList/GetPlaylistItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetVideoListServer).GetPlaylistItems(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetVideoList_ServiceDesc is the grpc.ServiceDesc for GetVideoList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetVideoList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getVideoList",
	HandlerType: (*GetVideoListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaylistItems",
			Handler:    _GetVideoList_GetPlaylistItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/getVideoService.proto",
}
